export const GET_USER_REQUEST = 'user/GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'user/GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'user/GET_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'user/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'user/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'user/UPDATE_USER_FAILURE';

export const SET_USER_PASSWORD_REQUEST = 'user/SET_USER_PASSWORD_REQUEST';
export const SET_USER_PASSWORD_SUCCESS = 'user/SET_USER_PASSWORD_SUCCESS';
export const SET_USER_PASSWORD_FAILURE = 'user/SET_USER_PASSWORD_FAILURE';

export const UPDATE_USER_PASSWORD_REQUEST = 'user/UPDATE_USER_PASSWORD_REQUEST';
export const UPDATE_USER_PASSWORD_SUCCESS = 'user/UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAILURE = 'user/UPDATE_USER_PASSWORD_FAILURE';

export const GET_USER_LIST_REQUEST = 'user/GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'user/GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'user/GET_USER_LIST_FAILURE';

export const DELETE_USER_REQUEST = 'user/DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'user/DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'user/DELETE_USER_FAILURE';

export const CREATE_USER_REQUEST = 'user/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'user/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'user/CREATE_USER_FAILURE';

export const RESET_PASSWORD_REQUEST = 'user/RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'user/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'user/RESET_PASSWORD_FAILURE';

export const GET_PASS_LIST_REQUEST = 'user/GET_PASS_LIST_REQUEST';
export const GET_PASS_LIST_SUCCESS = 'user/GET_PASS_LIST_SUCCESS';
export const GET_PASS_LIST_FAILURE = 'user/GET_PASS_LIST_FAILURE';

export const GET_WEB_PASS_LIST_ISSUED_BY_USER_REQUEST = 'user/GET_WEB_PASS_LIST_ISSUED_BY_USER_REQUEST';
export const GET_WEB_PASS_LIST_ISSUED_BY_USER_SUCCESS = 'user/GET_WEB_PASS_LIST_ISSUED_BY_USER_SUCCESS';
export const GET_WEB_PASS_LIST_ISSUED_BY_USER_FAILURE = 'user/GET_WEB_PASS_LIST_ISSUED_BY_USER_FAILURE';

export const GET_PASS_LIST_ISSUED_BY_USER_REQUEST = 'user/GET_PASS_LIST_ISSUED_BY_USER_REQUEST';
export const GET_PASS_LIST_ISSUED_BY_USER_SUCCESS = 'user/GET_PASS_LIST_ISSUED_BY_USER_SUCCESS';
export const GET_PASS_LIST_ISSUED_BY_USER_FAILURE = 'user/GET_PASS_LIST_ISSUED_BY_USER_FAILURE';
