
import { StyleSheet } from 'react-native';
import { spacing } from '../../../common/theme';

const { mbe16 } = spacing.spacingStyles;
const { gutterWidth } = spacing;

export default StyleSheet.create({
  fab: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    ...mbe16,
  },
  hack: {
    marginBottom: gutterWidth * 6.5, // this alpha generated by my head and eye
  },
});
